### ISSUE TITLE
address alias - name cannot be used until it is defined

### ISSUE THREAD

**Issue by ghost** [oltdaniel/clap#1]
The following assembly code can't be executed, because the named address is not defined yet.

```assembly
jump main
; Some variables
.nam main
; The main code
```

Suggested solution: Define the labels before, and set the address space afterwards. Example code:

```assembly
; Pre-define the name
.def main
; Jump to the alias
jump main
; Some variables
.nam main
; The main code

**Comment by KCreate** [comment]
They can be used! If your assembler encounters a label that is doesn't have an address for yet, it should just emit `0x00000000` into the instruction stream and mark the location as needing to be resolved. After you've generated your entire program, simply walk that table and fill in all the remaining addresses / offsets. If you encounter a label that you don't know, throw an error.

Check out how I solved this in my charly-vm:

https://github.com/KCreate/charly-vm/blob/master/include/assembler.h
https://github.com/KCreate/charly-vm/blob/master/src/compiler/assembler.cpp

**Comment by KCreate** [comment]
Yes, I assumed your problem was that you couldn‘t calculate the offsets to labels which weren‘t set before. Looking back, how would defining the labels beforehand have any effect on this?
